-- MINI-APLICATIE INSTAGRAM

-- Tabelul utilizatori
CREATE TABLE utilizatori (
    id_utilizator NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL
);

-- Tabelul prieteni (urm?riri unidirec?ionale)
CREATE TABLE prieteni (
    id_user1 NUMBER(10) NOT NULL, -- urm?re?te
    id_user2 NUMBER(10) NOT NULL, -- este urm?rit
    CONSTRAINT pk_prieteni PRIMARY KEY (id_user1, id_user2),
    CONSTRAINT fk_user1 FOREIGN KEY (id_user1) REFERENCES utilizatori(id_utilizator),
    CONSTRAINT fk_user2 FOREIGN KEY (id_user2) REFERENCES utilizatori(id_utilizator),
    CONSTRAINT chk_not_self_friend CHECK (id_user1 != id_user2)
);

-- Tabelul postari
CREATE TABLE postari (
    id_postare NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user NUMBER(10) NOT NULL,
    continut VARCHAR2(1000),
    data_postarii DATE DEFAULT SYSDATE,
    CONSTRAINT fk_postare_user FOREIGN KEY (id_user) REFERENCES utilizatori(id_utilizator)
);

-- INSERARE
INSERT INTO utilizatori (nume) VALUES ('Ana Pop');
INSERT INTO utilizatori (nume) VALUES ('Dan Ionescu');
INSERT INTO utilizatori (nume) VALUES ('Maria Radu');
INSERT INTO utilizatori (nume) VALUES ('Alex Dima');
INSERT INTO utilizatori (nume) VALUES ('Ioana Marinescu');
INSERT INTO utilizatori (nume) VALUES ('Vlad Georgescu');
INSERT INTO utilizatori (nume) VALUES ('Elena Stoica');
INSERT INTO utilizatori (nume) VALUES ('Robert Munteanu');
INSERT INTO utilizatori (nume) VALUES ('Diana Neagu');
INSERT INTO utilizatori (nume) VALUES ('Cristian Enache');

-- useri fara postari
INSERT INTO utilizatori (nume) VALUES ('Andreea Mihai');
INSERT INTO utilizatori (nume) VALUES ('Mihnea Dr?ghici');
INSERT INTO utilizatori (nume) VALUES ('Corina Vasilescu');
INSERT INTO utilizatori (nume) VALUES ('Florin Toma');
INSERT INTO utilizatori (nume) VALUES ('Bianca Marinescu');


INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 4);
INSERT INTO prieteni (id_user1, id_user2) VALUES (2, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (2, 5);
INSERT INTO prieteni (id_user1, id_user2) VALUES (3, 6);
INSERT INTO prieteni (id_user1, id_user2) VALUES (3, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 5);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 6);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 7);
INSERT INTO prieteni (id_user1, id_user2) VALUES (5, 8);
INSERT INTO prieteni (id_user1, id_user2) VALUES (6, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (6, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (7, 4);
INSERT INTO prieteni (id_user1, id_user2) VALUES (7, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (8, 9);
INSERT INTO prieteni (id_user1, id_user2) VALUES (9, 10);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 3);


-- Ana (id 1) - 4 post?ri
INSERT INTO postari (id_user, continut, data_postarii) VALUES (1, 'Zi frumoas? de prim?var?!', TO_DATE('2024-03-01','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (1, 'SQL e chiar fun!', TO_DATE('2024-03-03','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (1, 'Am terminat serialul!');
INSERT INTO postari (id_user, continut) VALUES (1, 'Cafea, c?r?i ?i lini?te.');

-- Dan (2) - 3 post?ri
INSERT INTO postari (id_user, continut, data_postarii) VALUES (2, 'Buna, tuturor!', TO_DATE('2024-03-10','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (2, 'Înv?? Oracle SQL.');
INSERT INTO postari (id_user, continut) VALUES (2, 'Sear? de coding.');

-- Maria (3) - 5 post?ri
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'Sesiune si stres!', TO_DATE('2025-03-01','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'În vacan?? la munte!', TO_DATE('2024-03-22','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'Apusuri superbe.', TO_DATE('2024-03-12','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (3, 'Dimine?i de weekend.');
INSERT INTO postari (id_user, continut) VALUES (3, 'Încerc o nou? re?et?.');

-- Alex (4) - 4 post?ri
INSERT INTO postari (id_user, continut, data_postarii) VALUES (4, 'Azi am fost productiv.', sysdate);
INSERT INTO postari (id_user, continut) VALUES (4, 'A?tept weekendul.');
INSERT INTO postari (id_user, continut) VALUES (4, 'Citeam despre baze de date.');
INSERT INTO postari (id_user, continut, data_postarii) VALUES (4, 'Plimbare în parc.',TO_DATE('2024-03-20','YYYY-MM-DD'));

-- Ioana (5) - 3 post?ri
INSERT INTO postari (id_user, continut) VALUES (5, 'Cafea cu prieteni.');
INSERT INTO postari (id_user, continut) VALUES (5, 'Un nou început.');
INSERT INTO postari (id_user, continut) VALUES (5, 'Prim?vara a sosit.');

-- Vlad (6) - 2 post?ri
INSERT INTO postari (id_user, continut) VALUES (6, 'Maraton de filme.');
INSERT INTO postari (id_user, continut) VALUES (6, 'Somn, mâncare, repaus.');

-- Elena (7) - 3 post?ri
INSERT INTO postari (id_user, continut) VALUES (7, 'Creez ceva nou!');
INSERT INTO postari (id_user, continut) VALUES (7, 'Florile mele înfloresc!');
INSERT INTO postari (id_user, continut) VALUES (7, 'Zi senin?!');

-- Robert (8) - 2 post?ri
INSERT INTO postari (id_user, continut) VALUES (8, 'Gata cu munca pe azi!');
INSERT INTO postari (id_user, continut) VALUES (8, 'Explor?ri urbane.');

-- Diana (9) - 2 post?ri
INSERT INTO postari (id_user, continut) VALUES (9, 'Book club');
INSERT INTO postari (id_user, continut) VALUES (9, 'Testez o nou? aplica?ie.');

-- Cristian (10) - 2 post?ri
INSERT INTO postari (id_user, continut) VALUES (10, 'SQL master incoming.');
INSERT INTO postari (id_user, continut) VALUES (10, 'Am finalizat proiectul!!!');

commit;


select * from utilizatori;
select * from postari;
select * from prieteni;

1. Afi?a?i o list? cu to?i utilizatorii ?i post?rile publicate de ace?tia. Se vor afi?a
inclusiv utilizatorii care nu au publicat nicio postare.
Se vor afi?a codul si numele utilizatorilor, împreuna cu codul ?i textul
post?rilor. Se vor ordona post?rile în func?ie de dat?, în ordine
descresc?toare, iar valorile NULL se vor afi?a la finalul valorilor diferite de
NULL.

SELECT pers.id_utilizator as "Cod utilizator", pers.nume as "Nume utilizator",  post.id_postare as "Cod postare", post.continut as "Text postare"
FROM utilizatori pers LEFT JOIN postari post
ON pers.id_utilizator = post.id_user
ORDER BY post.data_postarii DESC NULLS LAST;

2. Afi?a?i toate post?rile realizate în luna martie 2024 de c?tre prietenii
utilizatorului cu id-ul 1, cu excep?ia post?rilor realizate de utilizatorii care nu
îl urm?resc înapoi (adic? nu exist? rela?ia invers?).
S? se afi?eze codul ?i numele prietenului care a postat, con?inutul post?rii
?i data la care a fost realizat? postarea. Data o s? fie formatat? dd.mm.yyyy.
Se vor eticheta toate coloanele corespunz?tor.

SELECT post.id_user as "Cod utilizator", util.nume as "Nume utilizator", post.continut as "Continut postare", TO_CHAR(post.data_postarii, 'DD.MM.YYYY') as "Data postarii"
FROM postari post
JOIN utilizatori util 
ON post.id_user = util.id_utilizator
JOIN prieteni fr1 
ON fr1.id_user2 = post.id_user AND fr1.id_user1 = 1
JOIN prieteni fr2 
ON fr2.id_user1 = post.id_user AND fr2.id_user2 = 1
WHERE TO_CHAR(post.data_postarii, 'MM-YYYY') = '03-2024';

